###############################################################################
# Copyright 2017 Samsung Electronics All Rights Reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
###############################################################################

################ C EZMQ sample build script ##################
import os
Import('env')

cezmq_sample_env = env.Clone()
target_os = cezmq_sample_env.get('TARGET_OS')
target_arch = cezmq_sample_env.get('TARGET_ARCH')

######################################################################
# Build flags
######################################################################
cezmq_sample_env.AppendUnique(CPPPATH=[
    '../include',
])

cezmq_sample_env.AppendUnique(
    CXXFLAGS=['-O2', '-g', '-Wall', '-fmessage-length=0', '-std=c++0x', '-I/usr/local/include'])

if cezmq_sample_env.get('RELEASE'):
	cezmq_sample_env.PrependUnique(LIBS=['ezmq'], LIBPATH=[os.path.join('./../dependencies/protocol-ezmq-cpp/out/linux/', target_arch, 'release')])
else:
	cezmq_sample_env.PrependUnique(LIBS=['ezmq'], LIBPATH=[os.path.join('./../dependencies/protocol-ezmq-cpp/out/linux/', target_arch, 'debug')])

cezmq_sample_env.AppendUnique(LIBS=['cezmq'])

####################################################################
# Source files and Targets
######################################################################
cezmqsubscriber = cezmq_sample_env.Program('csubscriber', 'csubscriber.c')
cezmqpublisher = cezmq_sample_env.Program('cpublisher', 'cpublisher.c')

